# Form implementation generated from reading ui file '.\templates\dlgAbout.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgAbout(object):
    def setupUi(self, dlgAbout):
        dlgAbout.setObjectName("dlgAbout")
        dlgAbout.resize(500, 400)
        dlgAbout.setModal(True)
        self.image = QtWidgets.QLabel(parent=dlgAbout)
        self.image.setGeometry(QtCore.QRect(120, 10, 251, 241))
        self.image.setText("")
        self.image.setPixmap(QtGui.QPixmap(".\\img\\logo.png"))
        self.image.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.image.setWordWrap(False)
        self.image.setObjectName("image")
        self.lblVersion = QtWidgets.QLabel(parent=dlgAbout)
        self.lblVersion.setGeometry(QtCore.QRect(170, 260, 150, 25))
        self.lblVersion.setMinimumSize(QtCore.QSize(150, 25))
        self.lblVersion.setMaximumSize(QtCore.QSize(150, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblVersion.setFont(font)
        self.lblVersion.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblVersion.setObjectName("lblVersion")
        self.btnCloseabout = QtWidgets.QPushButton(parent=dlgAbout)
        self.btnCloseabout.setGeometry(QtCore.QRect(210, 350, 80, 25))
        self.btnCloseabout.setMinimumSize(QtCore.QSize(80, 25))
        self.btnCloseabout.setSizeIncrement(QtCore.QSize(80, 25))
        self.btnCloseabout.setObjectName("btnCloseabout")
        self.lblAutor = QtWidgets.QLabel(parent=dlgAbout)
        self.lblAutor.setGeometry(QtCore.QRect(120, 300, 250, 25))
        self.lblAutor.setMinimumSize(QtCore.QSize(250, 25))
        self.lblAutor.setMaximumSize(QtCore.QSize(250, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblAutor.setFont(font)
        self.lblAutor.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblAutor.setObjectName("lblAutor")

        self.retranslateUi(dlgAbout)
        QtCore.QMetaObject.connectSlotsByName(dlgAbout)

    def retranslateUi(self, dlgAbout):
        _translate = QtCore.QCoreApplication.translate
        dlgAbout.setWindowTitle(_translate("dlgAbout", "Dialog"))
        self.lblVersion.setText(_translate("dlgAbout", "Version 0.0.1"))
        self.btnCloseabout.setText(_translate("dlgAbout", "Close"))
        self.lblAutor.setText(_translate("dlgAbout", "Autor: Johan Aponte \u00a9"))
