# Form implementation generated from reading ui file '.\templates\dlgAbout.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgAbout(object):
    def setupUi(self, dlgAbout):
        dlgAbout.setObjectName("dlgAbout")
        dlgAbout.resize(500, 400)
        dlgAbout.setMinimumSize(QtCore.QSize(500, 400))
        dlgAbout.setMaximumSize(QtCore.QSize(500, 400))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\templates\\../../../Downloads/logo.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        dlgAbout.setWindowIcon(icon)
        dlgAbout.setModal(True)
        self.btnCloseabout = QtWidgets.QPushButton(parent=dlgAbout)
        self.btnCloseabout.setGeometry(QtCore.QRect(210, 340, 80, 25))
        self.btnCloseabout.setMinimumSize(QtCore.QSize(80, 25))
        self.btnCloseabout.setMaximumSize(QtCore.QSize(80, 25))
        self.btnCloseabout.setObjectName("btnCloseabout")
        self.label = QtWidgets.QLabel(parent=dlgAbout)
        self.label.setGeometry(QtCore.QRect(270, 120, 47, 13))
        self.label.setText("")
        self.label.setObjectName("label")
        self.lblversion = QtWidgets.QLabel(parent=dlgAbout)
        self.lblversion.setGeometry(QtCore.QRect(180, 220, 150, 25))
        self.lblversion.setMinimumSize(QtCore.QSize(150, 25))
        self.lblversion.setMaximumSize(QtCore.QSize(150, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lblversion.setFont(font)
        self.lblversion.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblversion.setObjectName("lblversion")
        self.label_3 = QtWidgets.QLabel(parent=dlgAbout)
        self.label_3.setGeometry(QtCore.QRect(170, 30, 150, 150))
        self.label_3.setMaximumSize(QtCore.QSize(180, 180))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(".\\templates\\../../../Downloads/logo.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setWordWrap(False)
        self.label_3.setObjectName("label_3")
        self.lblautor = QtWidgets.QLabel(parent=dlgAbout)
        self.lblautor.setGeometry(QtCore.QRect(130, 280, 250, 25))
        self.lblautor.setMinimumSize(QtCore.QSize(250, 25))
        self.lblautor.setMaximumSize(QtCore.QSize(250, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lblautor.setFont(font)
        self.lblautor.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblautor.setObjectName("lblautor")

        self.retranslateUi(dlgAbout)
        QtCore.QMetaObject.connectSlotsByName(dlgAbout)

    def retranslateUi(self, dlgAbout):
        _translate = QtCore.QCoreApplication.translate
        dlgAbout.setWindowTitle(_translate("dlgAbout", "Dialog"))
        self.btnCloseabout.setText(_translate("dlgAbout", "Close"))
        self.lblversion.setText(_translate("dlgAbout", "Version 0.0.1"))
        self.lblautor.setText(_translate("dlgAbout", "Author: Esteban Gonzalez Poyet ©"))
